### PR TITLE
add missing IERR argument to NORTEST

### PR DESCRIPTION
**Pull request by jsta**
See #27 and https://stackoverflow.com/q/45270145/3362993

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Looks good to me! Sounds like an epic troubleshooting session. Can you bump up the version number to `0.7.12`. I'll cut a release after that and push it up to GRAN. Thanks so much!

**Comment by aappling-usgs** [comment]
Nice work, @jsta !

**Comment by jsta** [comment]
@ldecicco-USGS Did you mean bump the version to `0.7.13`?

**Comment by ldecicco-USGS** [comment]
whoops, yup.

**Pull request merged**
