### PR TITLE
Check for empty return

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
Empty returns were freezing the code at as.qw.

TODO, get the empty return to match a non-empty one.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
testing it out
```r
> c <- importNWISqw('05330000',c('00400','00403'),begin.date='2008-01-01') # used to freeze, now runs
Do data returned
Error in ByResults$Seq <- numeric() : object 'ByResults' not found
```
1. No longer freezes!
2. Maybe "Do" should be "No"?
3. Error =(

**Comment by ldecicco-USGS** [comment]
Details!

**Comment by ldecicco-USGS** [comment]
Huh, didn't error here....I'll check

**Comment by ldecicco-USGS** [comment]
Test the new one before I tag another release

**Comment by aappling-usgs** [comment]
```r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] smwrQW_0.7.10       smwrStats_0.7.5     smwrGraphs_1.1.1    smwrBase_1.1.2      lubridate_1.5.0     dataRetrieval_2.4.8
```

**Comment by aappling-usgs** [comment]
Test which new one?

**Comment by ldecicco-USGS** [comment]
The PR I just committed like 1 minute ago

**Pull request merged**
